version: "3.1"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-client-client
    volumes:
      - .:/app
    ports:
      - 8001:8001
    command: "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
